export const CSS_TOPICS = [
  'CSS Introduction',
  'CSS Types',
  'Tag Selectors',
  'Grouping Selectors',
  'Colors',
  'Typography',
  'Text Styles',
  'Margin',
  'Div and Span',
  'ID and Class',
  'Backgrounds',
  'Width and Size',
  'Box Model',
  'Nth-Child',
  'Descendant Selectors',
  'First-of-Type',
  'Pseudo Classes',
  'Borders',
  'CSS Units',
  'List Style',
  'Line-Height',
  'Specificity',
  'Float and Clear',
  'Display Properties',
  'Flexbox',
  'Grid',
  'Visibility',
  'Cursor',
  'calc()',
  'Positioning',
  'Z-Index',
  'Overflow',
  'Multiple Backgrounds',
  'Word-Wrap',
  'Border-Radius',
  'Box-Shadow',
  'Text-Shadow',
  'Transforms',
  'Root Element',
  'CSS Variables',
  'Transitions',
  'Animations'
];
